import { Niche } from "./Niche";

export interface Influencer {
  id: string;
  name: string;
  username: string;
  email: string;
  emailVisibility: boolean;
  full_name: string;
  bio: string;
  background_img: string;
  profile_img: string;
  cell_phone: number;
  birth_date: string;
  country: string;
  state: string;
  city: string;
  neighborhood: string;
  street: string;
  address_num: number;
  cep: number;
  complement: string;
  pix_key: string;
  media_kit_url: string;
  extra_skills: string | null;
  portifolio_questions: string[];
  previous_work_imgs: string[];
  brands_worked_imgs: string[];
  instagram_url: string;
  instagram_followers_number: string;
  facebook_url: string;
  facebook_followers_number: string;
  linkedin_url: string;
  linkedin_followers_number: string;
  youtube_url: string;
  youtube_subscribers_number: string;
  tiktok_url: string;
  tiktok_followers_number: string;
  twitter_url: string;
  twitter_followers_number: string;
  twitch_url: string;
  twitch_followers_number: string;
  yourclub_url: string;
  yourclub_followers_number: string;
  kwai_url: string;
  kwai_followers_number: string;
  pinterest_url: string;
  pinterest_followers_number: string;
  languages: string[] | null;
  niche: string[];
  account_type: string;
  gender: string;
  verified: boolean;
  top_creator: boolean;
  stories_price: number;
  feed_price: number;
  reels_price: number;
  ugc_price: number;
  created: Date;
  updated: Date;
  collectionId: string;
  collectionName: string;
  expand?: {
    niche: Niche[];
  };
}
