/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermosIndexImport } from './routes/termos/index'
import { Route as PrivacidadeIndexImport } from './routes/privacidade/index'
import { Route as ContratoCampanhaIndexImport } from './routes/contrato-campanha/index'
import { Route as dashboardSideNavDashboardImport } from './routes/(dashboard)/_side-nav-dashboard'
import { Route as authLogin123newIndexImport } from './routes/(auth)/login123new/index'
import { Route as authEsquecerSenhaIndexImport } from './routes/(auth)/esquecer-senha/index'
import { Route as authCadastroIndexImport } from './routes/(auth)/cadastro/index'
import { Route as authCadastroMarcaImport } from './routes/(auth)/cadastro/marca'
import { Route as authCadastroCreatorImport } from './routes/(auth)/cadastro/creator'
import { Route as dashboardSideNavDashboardVitrineDeCampanhasIndexImport } from './routes/(dashboard)/_side-nav-dashboard/vitrine-de-campanhas/index'
import { Route as dashboardSideNavDashboardTopCreatorIndexImport } from './routes/(dashboard)/_side-nav-dashboard/top-creator/index'
import { Route as dashboardSideNavDashboardNotificacoesIndexImport } from './routes/(dashboard)/_side-nav-dashboard/notificacoes/index'
import { Route as dashboardSideNavDashboardDashboardIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/index'
import { Route as dashboardSideNavDashboardDashboardMarcaIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard-marca/index'
import { Route as dashboardSideNavDashboardDashboardCreatorIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard-creator/index'
import { Route as dashboardSideNavDashboardDashboardLayoutImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/_layout'
import { Route as dashboardSideNavDashboardDashboardCriarIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/criar/index'
import { Route as dashboardSideNavDashboardDashboardChatIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/chat/index'
import { Route as dashboardSideNavDashboardDashboardCampanhasIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/campanhas/index'
import { Route as dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard-marca/criar-campanha/index'
import { Route as dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/index'
import { Route as dashboardSideNavDashboardperfisMarcaUserNameIndexImport } from './routes/(dashboard)/_side-nav-dashboard/(perfis)/marca/$userName/index'
import { Route as dashboardSideNavDashboardperfisCreatorUsernameIndexImport } from './routes/(dashboard)/_side-nav-dashboard/(perfis)/creator/$username/index'
import { Route as dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar'
import { Route as dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar'
import { Route as dashboardSideNavDashboardDashboardCampanhasCampaignIdAplicarImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/aplicar'
import { Route as dashboardSideNavDashboardperfisMarcaUserNameEditarIndexImport } from './routes/(dashboard)/_side-nav-dashboard/(perfis)/marca/$userName/editar/index'
import { Route as dashboardSideNavDashboardperfisCreatorUsernameEditarIndexImport } from './routes/(dashboard)/_side-nav-dashboard/(perfis)/creator/$username/editar/index'

// Create Virtual Routes

const dashboardImport = createFileRoute('/(dashboard)')()
const IndexLazyImport = createFileRoute('/')()
const dashboardSideNavDashboardDashboardImport = createFileRoute(
  '/(dashboard)/_side-nav-dashboard/dashboard',
)()

// Create/Update Routes

const dashboardRoute = dashboardImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TermosIndexRoute = TermosIndexImport.update({
  path: '/termos/',
  getParentRoute: () => rootRoute,
} as any)

const PrivacidadeIndexRoute = PrivacidadeIndexImport.update({
  path: '/privacidade/',
  getParentRoute: () => rootRoute,
} as any)

const ContratoCampanhaIndexRoute = ContratoCampanhaIndexImport.update({
  path: '/contrato-campanha/',
  getParentRoute: () => rootRoute,
} as any)

const dashboardSideNavDashboardRoute = dashboardSideNavDashboardImport.update({
  id: '/_side-nav-dashboard',
  getParentRoute: () => dashboardRoute,
} as any)

const dashboardSideNavDashboardDashboardRoute =
  dashboardSideNavDashboardDashboardImport.update({
    path: '/dashboard',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const authLogin123newIndexRoute = authLogin123newIndexImport.update({
  path: '/login123new/',
  getParentRoute: () => rootRoute,
} as any)

const authEsquecerSenhaIndexRoute = authEsquecerSenhaIndexImport.update({
  path: '/esquecer-senha/',
  getParentRoute: () => rootRoute,
} as any)

const authCadastroIndexRoute = authCadastroIndexImport.update({
  path: '/cadastro/',
  getParentRoute: () => rootRoute,
} as any)

const authCadastroMarcaRoute = authCadastroMarcaImport.update({
  path: '/cadastro/marca',
  getParentRoute: () => rootRoute,
} as any)

const authCadastroCreatorRoute = authCadastroCreatorImport.update({
  path: '/cadastro/creator',
  getParentRoute: () => rootRoute,
} as any)

const dashboardSideNavDashboardVitrineDeCampanhasIndexRoute =
  dashboardSideNavDashboardVitrineDeCampanhasIndexImport.update({
    path: '/vitrine-de-campanhas/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardTopCreatorIndexRoute =
  dashboardSideNavDashboardTopCreatorIndexImport.update({
    path: '/top-creator/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardNotificacoesIndexRoute =
  dashboardSideNavDashboardNotificacoesIndexImport.update({
    path: '/notificacoes/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardIndexRoute =
  dashboardSideNavDashboardDashboardIndexImport.update({
    path: '/',
    getParentRoute: () => dashboardSideNavDashboardDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardMarcaIndexRoute =
  dashboardSideNavDashboardDashboardMarcaIndexImport.update({
    path: '/dashboard-marca/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardCreatorIndexRoute =
  dashboardSideNavDashboardDashboardCreatorIndexImport.update({
    path: '/dashboard-creator/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardLayoutRoute =
  dashboardSideNavDashboardDashboardLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => dashboardSideNavDashboardDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardCriarIndexRoute =
  dashboardSideNavDashboardDashboardCriarIndexImport.update({
    path: '/criar/',
    getParentRoute: () => dashboardSideNavDashboardDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardChatIndexRoute =
  dashboardSideNavDashboardDashboardChatIndexImport.update({
    path: '/chat/',
    getParentRoute: () => dashboardSideNavDashboardDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardCampanhasIndexRoute =
  dashboardSideNavDashboardDashboardCampanhasIndexImport.update({
    path: '/campanhas/',
    getParentRoute: () => dashboardSideNavDashboardDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute =
  dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexImport.update({
    path: '/dashboard-marca/criar-campanha/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute =
  dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexImport.update({
    path: '/campanhas/$campaignId/',
    getParentRoute: () => dashboardSideNavDashboardDashboardRoute,
  } as any)

const dashboardSideNavDashboardperfisMarcaUserNameIndexRoute =
  dashboardSideNavDashboardperfisMarcaUserNameIndexImport.update({
    path: '/marca/$userName/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardperfisCreatorUsernameIndexRoute =
  dashboardSideNavDashboardperfisCreatorUsernameIndexImport.update({
    path: '/creator/$username/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute =
  dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarImport.update({
    path: '/campanhas/$campaignId/editar',
    getParentRoute: () => dashboardSideNavDashboardDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute =
  dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarImport.update({
    path: '/campanhas/$campaignId/aprovar',
    getParentRoute: () => dashboardSideNavDashboardDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardCampanhasCampaignIdAplicarRoute =
  dashboardSideNavDashboardDashboardCampanhasCampaignIdAplicarImport.update({
    path: '/campanhas/$campaignId/aplicar',
    getParentRoute: () => dashboardSideNavDashboardDashboardRoute,
  } as any)

const dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute =
  dashboardSideNavDashboardperfisMarcaUserNameEditarIndexImport.update({
    path: '/marca/$userName/editar/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute =
  dashboardSideNavDashboardperfisCreatorUsernameEditarIndexImport.update({
    path: '/creator/$username/editar/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/_side-nav-dashboard': {
      id: '/_side-nav-dashboard'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardSideNavDashboardImport
      parentRoute: typeof dashboardRoute
    }
    '/contrato-campanha/': {
      id: '/contrato-campanha/'
      path: '/contrato-campanha'
      fullPath: '/contrato-campanha'
      preLoaderRoute: typeof ContratoCampanhaIndexImport
      parentRoute: typeof rootRoute
    }
    '/privacidade/': {
      id: '/privacidade/'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeIndexImport
      parentRoute: typeof rootRoute
    }
    '/termos/': {
      id: '/termos/'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/cadastro/creator': {
      id: '/cadastro/creator'
      path: '/cadastro/creator'
      fullPath: '/cadastro/creator'
      preLoaderRoute: typeof authCadastroCreatorImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/cadastro/marca': {
      id: '/cadastro/marca'
      path: '/cadastro/marca'
      fullPath: '/cadastro/marca'
      preLoaderRoute: typeof authCadastroMarcaImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/cadastro/': {
      id: '/cadastro/'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof authCadastroIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/esquecer-senha/': {
      id: '/esquecer-senha/'
      path: '/esquecer-senha'
      fullPath: '/esquecer-senha'
      preLoaderRoute: typeof authEsquecerSenhaIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login123new/': {
      id: '/login123new/'
      path: '/login123new'
      fullPath: '/login123new'
      preLoaderRoute: typeof authLogin123newIndexImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/_side-nav-dashboard/dashboard': {
      id: '/_side-nav-dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/_layout': {
      id: '/_side-nav-dashboard/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardLayoutImport
      parentRoute: typeof dashboardSideNavDashboardDashboardRoute
    }
    '/(dashboard)/_side-nav-dashboard/dashboard-creator/': {
      id: '/_side-nav-dashboard/dashboard-creator/'
      path: '/dashboard-creator'
      fullPath: '/dashboard-creator'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardCreatorIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard-marca/': {
      id: '/_side-nav-dashboard/dashboard-marca/'
      path: '/dashboard-marca'
      fullPath: '/dashboard-marca'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardMarcaIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/': {
      id: '/_side-nav-dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardIndexImport
      parentRoute: typeof dashboardSideNavDashboardDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/notificacoes/': {
      id: '/_side-nav-dashboard/notificacoes/'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof dashboardSideNavDashboardNotificacoesIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/top-creator/': {
      id: '/_side-nav-dashboard/top-creator/'
      path: '/top-creator'
      fullPath: '/top-creator'
      preLoaderRoute: typeof dashboardSideNavDashboardTopCreatorIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/vitrine-de-campanhas/': {
      id: '/_side-nav-dashboard/vitrine-de-campanhas/'
      path: '/vitrine-de-campanhas'
      fullPath: '/vitrine-de-campanhas'
      preLoaderRoute: typeof dashboardSideNavDashboardVitrineDeCampanhasIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard-marca/criar-campanha/': {
      id: '/_side-nav-dashboard/dashboard-marca/criar-campanha/'
      path: '/dashboard-marca/criar-campanha'
      fullPath: '/dashboard-marca/criar-campanha'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/campanhas/': {
      id: '/_side-nav-dashboard/dashboard/campanhas/'
      path: '/campanhas'
      fullPath: '/dashboard/campanhas'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardCampanhasIndexImport
      parentRoute: typeof dashboardSideNavDashboardDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/chat/': {
      id: '/_side-nav-dashboard/dashboard/chat/'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardChatIndexImport
      parentRoute: typeof dashboardSideNavDashboardDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/criar/': {
      id: '/_side-nav-dashboard/dashboard/criar/'
      path: '/criar'
      fullPath: '/dashboard/criar'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardCriarIndexImport
      parentRoute: typeof dashboardSideNavDashboardDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/aplicar': {
      id: '/_side-nav-dashboard/dashboard/campanhas/$campaignId/aplicar'
      path: '/campanhas/$campaignId/aplicar'
      fullPath: '/dashboard/campanhas/$campaignId/aplicar'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAplicarImport
      parentRoute: typeof dashboardSideNavDashboardDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar': {
      id: '/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar'
      path: '/campanhas/$campaignId/aprovar'
      fullPath: '/dashboard/campanhas/$campaignId/aprovar'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarImport
      parentRoute: typeof dashboardSideNavDashboardDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar': {
      id: '/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar'
      path: '/campanhas/$campaignId/editar'
      fullPath: '/dashboard/campanhas/$campaignId/editar'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarImport
      parentRoute: typeof dashboardSideNavDashboardDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/(perfis)/creator/$username/': {
      id: '/_side-nav-dashboard/creator/$username/'
      path: '/creator/$username'
      fullPath: '/creator/$username'
      preLoaderRoute: typeof dashboardSideNavDashboardperfisCreatorUsernameIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/(perfis)/marca/$userName/': {
      id: '/_side-nav-dashboard/marca/$userName/'
      path: '/marca/$userName'
      fullPath: '/marca/$userName'
      preLoaderRoute: typeof dashboardSideNavDashboardperfisMarcaUserNameIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/': {
      id: '/_side-nav-dashboard/dashboard/campanhas/$campaignId/'
      path: '/campanhas/$campaignId'
      fullPath: '/dashboard/campanhas/$campaignId'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexImport
      parentRoute: typeof dashboardSideNavDashboardDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/(perfis)/creator/$username/editar/': {
      id: '/_side-nav-dashboard/creator/$username/editar/'
      path: '/creator/$username/editar'
      fullPath: '/creator/$username/editar'
      preLoaderRoute: typeof dashboardSideNavDashboardperfisCreatorUsernameEditarIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/(perfis)/marca/$userName/editar/': {
      id: '/_side-nav-dashboard/marca/$userName/editar/'
      path: '/marca/$userName/editar'
      fullPath: '/marca/$userName/editar'
      preLoaderRoute: typeof dashboardSideNavDashboardperfisMarcaUserNameEditarIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
  }
}

// Create and export the route tree

interface dashboardSideNavDashboardDashboardRouteChildren {
  dashboardSideNavDashboardDashboardLayoutRoute: typeof dashboardSideNavDashboardDashboardLayoutRoute
  dashboardSideNavDashboardDashboardIndexRoute: typeof dashboardSideNavDashboardDashboardIndexRoute
  dashboardSideNavDashboardDashboardCampanhasIndexRoute: typeof dashboardSideNavDashboardDashboardCampanhasIndexRoute
  dashboardSideNavDashboardDashboardChatIndexRoute: typeof dashboardSideNavDashboardDashboardChatIndexRoute
  dashboardSideNavDashboardDashboardCriarIndexRoute: typeof dashboardSideNavDashboardDashboardCriarIndexRoute
  dashboardSideNavDashboardDashboardCampanhasCampaignIdAplicarRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAplicarRoute
  dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute
  dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute
  dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute
}

const dashboardSideNavDashboardDashboardRouteChildren: dashboardSideNavDashboardDashboardRouteChildren =
  {
    dashboardSideNavDashboardDashboardLayoutRoute:
      dashboardSideNavDashboardDashboardLayoutRoute,
    dashboardSideNavDashboardDashboardIndexRoute:
      dashboardSideNavDashboardDashboardIndexRoute,
    dashboardSideNavDashboardDashboardCampanhasIndexRoute:
      dashboardSideNavDashboardDashboardCampanhasIndexRoute,
    dashboardSideNavDashboardDashboardChatIndexRoute:
      dashboardSideNavDashboardDashboardChatIndexRoute,
    dashboardSideNavDashboardDashboardCriarIndexRoute:
      dashboardSideNavDashboardDashboardCriarIndexRoute,
    dashboardSideNavDashboardDashboardCampanhasCampaignIdAplicarRoute:
      dashboardSideNavDashboardDashboardCampanhasCampaignIdAplicarRoute,
    dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute:
      dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute,
    dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute:
      dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute,
    dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute:
      dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute,
  }

const dashboardSideNavDashboardDashboardRouteWithChildren =
  dashboardSideNavDashboardDashboardRoute._addFileChildren(
    dashboardSideNavDashboardDashboardRouteChildren,
  )

interface dashboardSideNavDashboardRouteChildren {
  dashboardSideNavDashboardDashboardRoute: typeof dashboardSideNavDashboardDashboardRouteWithChildren
  dashboardSideNavDashboardDashboardCreatorIndexRoute: typeof dashboardSideNavDashboardDashboardCreatorIndexRoute
  dashboardSideNavDashboardDashboardMarcaIndexRoute: typeof dashboardSideNavDashboardDashboardMarcaIndexRoute
  dashboardSideNavDashboardNotificacoesIndexRoute: typeof dashboardSideNavDashboardNotificacoesIndexRoute
  dashboardSideNavDashboardTopCreatorIndexRoute: typeof dashboardSideNavDashboardTopCreatorIndexRoute
  dashboardSideNavDashboardVitrineDeCampanhasIndexRoute: typeof dashboardSideNavDashboardVitrineDeCampanhasIndexRoute
  dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute: typeof dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute
  dashboardSideNavDashboardperfisCreatorUsernameIndexRoute: typeof dashboardSideNavDashboardperfisCreatorUsernameIndexRoute
  dashboardSideNavDashboardperfisMarcaUserNameIndexRoute: typeof dashboardSideNavDashboardperfisMarcaUserNameIndexRoute
  dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute: typeof dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute
  dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute: typeof dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute
}

const dashboardSideNavDashboardRouteChildren: dashboardSideNavDashboardRouteChildren =
  {
    dashboardSideNavDashboardDashboardRoute:
      dashboardSideNavDashboardDashboardRouteWithChildren,
    dashboardSideNavDashboardDashboardCreatorIndexRoute:
      dashboardSideNavDashboardDashboardCreatorIndexRoute,
    dashboardSideNavDashboardDashboardMarcaIndexRoute:
      dashboardSideNavDashboardDashboardMarcaIndexRoute,
    dashboardSideNavDashboardNotificacoesIndexRoute:
      dashboardSideNavDashboardNotificacoesIndexRoute,
    dashboardSideNavDashboardTopCreatorIndexRoute:
      dashboardSideNavDashboardTopCreatorIndexRoute,
    dashboardSideNavDashboardVitrineDeCampanhasIndexRoute:
      dashboardSideNavDashboardVitrineDeCampanhasIndexRoute,
    dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute:
      dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute,
    dashboardSideNavDashboardperfisCreatorUsernameIndexRoute:
      dashboardSideNavDashboardperfisCreatorUsernameIndexRoute,
    dashboardSideNavDashboardperfisMarcaUserNameIndexRoute:
      dashboardSideNavDashboardperfisMarcaUserNameIndexRoute,
    dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute:
      dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute,
    dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute:
      dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute,
  }

const dashboardSideNavDashboardRouteWithChildren =
  dashboardSideNavDashboardRoute._addFileChildren(
    dashboardSideNavDashboardRouteChildren,
  )

interface dashboardRouteChildren {
  dashboardSideNavDashboardRoute: typeof dashboardSideNavDashboardRouteWithChildren
}

const dashboardRouteChildren: dashboardRouteChildren = {
  dashboardSideNavDashboardRoute: dashboardSideNavDashboardRouteWithChildren,
}

const dashboardRouteWithChildren = dashboardRoute._addFileChildren(
  dashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof dashboardSideNavDashboardRouteWithChildren
  '/contrato-campanha': typeof ContratoCampanhaIndexRoute
  '/privacidade': typeof PrivacidadeIndexRoute
  '/termos': typeof TermosIndexRoute
  '/cadastro/creator': typeof authCadastroCreatorRoute
  '/cadastro/marca': typeof authCadastroMarcaRoute
  '/cadastro': typeof authCadastroIndexRoute
  '/esquecer-senha': typeof authEsquecerSenhaIndexRoute
  '/login123new': typeof authLogin123newIndexRoute
  '/dashboard': typeof dashboardSideNavDashboardDashboardLayoutRoute
  '/dashboard-creator': typeof dashboardSideNavDashboardDashboardCreatorIndexRoute
  '/dashboard-marca': typeof dashboardSideNavDashboardDashboardMarcaIndexRoute
  '/dashboard/': typeof dashboardSideNavDashboardDashboardIndexRoute
  '/notificacoes': typeof dashboardSideNavDashboardNotificacoesIndexRoute
  '/top-creator': typeof dashboardSideNavDashboardTopCreatorIndexRoute
  '/vitrine-de-campanhas': typeof dashboardSideNavDashboardVitrineDeCampanhasIndexRoute
  '/dashboard-marca/criar-campanha': typeof dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute
  '/dashboard/campanhas': typeof dashboardSideNavDashboardDashboardCampanhasIndexRoute
  '/dashboard/chat': typeof dashboardSideNavDashboardDashboardChatIndexRoute
  '/dashboard/criar': typeof dashboardSideNavDashboardDashboardCriarIndexRoute
  '/dashboard/campanhas/$campaignId/aplicar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAplicarRoute
  '/dashboard/campanhas/$campaignId/aprovar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute
  '/dashboard/campanhas/$campaignId/editar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute
  '/creator/$username': typeof dashboardSideNavDashboardperfisCreatorUsernameIndexRoute
  '/marca/$userName': typeof dashboardSideNavDashboardperfisMarcaUserNameIndexRoute
  '/dashboard/campanhas/$campaignId': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute
  '/creator/$username/editar': typeof dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute
  '/marca/$userName/editar': typeof dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof dashboardSideNavDashboardRouteWithChildren
  '/contrato-campanha': typeof ContratoCampanhaIndexRoute
  '/privacidade': typeof PrivacidadeIndexRoute
  '/termos': typeof TermosIndexRoute
  '/cadastro/creator': typeof authCadastroCreatorRoute
  '/cadastro/marca': typeof authCadastroMarcaRoute
  '/cadastro': typeof authCadastroIndexRoute
  '/esquecer-senha': typeof authEsquecerSenhaIndexRoute
  '/login123new': typeof authLogin123newIndexRoute
  '/dashboard': typeof dashboardSideNavDashboardDashboardIndexRoute
  '/dashboard-creator': typeof dashboardSideNavDashboardDashboardCreatorIndexRoute
  '/dashboard-marca': typeof dashboardSideNavDashboardDashboardMarcaIndexRoute
  '/notificacoes': typeof dashboardSideNavDashboardNotificacoesIndexRoute
  '/top-creator': typeof dashboardSideNavDashboardTopCreatorIndexRoute
  '/vitrine-de-campanhas': typeof dashboardSideNavDashboardVitrineDeCampanhasIndexRoute
  '/dashboard-marca/criar-campanha': typeof dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute
  '/dashboard/campanhas': typeof dashboardSideNavDashboardDashboardCampanhasIndexRoute
  '/dashboard/chat': typeof dashboardSideNavDashboardDashboardChatIndexRoute
  '/dashboard/criar': typeof dashboardSideNavDashboardDashboardCriarIndexRoute
  '/dashboard/campanhas/$campaignId/aplicar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAplicarRoute
  '/dashboard/campanhas/$campaignId/aprovar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute
  '/dashboard/campanhas/$campaignId/editar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute
  '/creator/$username': typeof dashboardSideNavDashboardperfisCreatorUsernameIndexRoute
  '/marca/$userName': typeof dashboardSideNavDashboardperfisMarcaUserNameIndexRoute
  '/dashboard/campanhas/$campaignId': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute
  '/creator/$username/editar': typeof dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute
  '/marca/$userName/editar': typeof dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof dashboardRouteWithChildren
  '/_side-nav-dashboard': typeof dashboardSideNavDashboardRouteWithChildren
  '/contrato-campanha/': typeof ContratoCampanhaIndexRoute
  '/privacidade/': typeof PrivacidadeIndexRoute
  '/termos/': typeof TermosIndexRoute
  '/cadastro/creator': typeof authCadastroCreatorRoute
  '/cadastro/marca': typeof authCadastroMarcaRoute
  '/cadastro/': typeof authCadastroIndexRoute
  '/esquecer-senha/': typeof authEsquecerSenhaIndexRoute
  '/login123new/': typeof authLogin123newIndexRoute
  '/_side-nav-dashboard/dashboard': typeof dashboardSideNavDashboardDashboardRouteWithChildren
  '/_side-nav-dashboard/dashboard/_layout': typeof dashboardSideNavDashboardDashboardLayoutRoute
  '/_side-nav-dashboard/dashboard-creator/': typeof dashboardSideNavDashboardDashboardCreatorIndexRoute
  '/_side-nav-dashboard/dashboard-marca/': typeof dashboardSideNavDashboardDashboardMarcaIndexRoute
  '/_side-nav-dashboard/dashboard/': typeof dashboardSideNavDashboardDashboardIndexRoute
  '/_side-nav-dashboard/notificacoes/': typeof dashboardSideNavDashboardNotificacoesIndexRoute
  '/_side-nav-dashboard/top-creator/': typeof dashboardSideNavDashboardTopCreatorIndexRoute
  '/_side-nav-dashboard/vitrine-de-campanhas/': typeof dashboardSideNavDashboardVitrineDeCampanhasIndexRoute
  '/_side-nav-dashboard/dashboard-marca/criar-campanha/': typeof dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute
  '/_side-nav-dashboard/dashboard/campanhas/': typeof dashboardSideNavDashboardDashboardCampanhasIndexRoute
  '/_side-nav-dashboard/dashboard/chat/': typeof dashboardSideNavDashboardDashboardChatIndexRoute
  '/_side-nav-dashboard/dashboard/criar/': typeof dashboardSideNavDashboardDashboardCriarIndexRoute
  '/_side-nav-dashboard/dashboard/campanhas/$campaignId/aplicar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAplicarRoute
  '/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute
  '/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute
  '/_side-nav-dashboard/creator/$username/': typeof dashboardSideNavDashboardperfisCreatorUsernameIndexRoute
  '/_side-nav-dashboard/marca/$userName/': typeof dashboardSideNavDashboardperfisMarcaUserNameIndexRoute
  '/_side-nav-dashboard/dashboard/campanhas/$campaignId/': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute
  '/_side-nav-dashboard/creator/$username/editar/': typeof dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute
  '/_side-nav-dashboard/marca/$userName/editar/': typeof dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contrato-campanha'
    | '/privacidade'
    | '/termos'
    | '/cadastro/creator'
    | '/cadastro/marca'
    | '/cadastro'
    | '/esquecer-senha'
    | '/login123new'
    | '/dashboard'
    | '/dashboard-creator'
    | '/dashboard-marca'
    | '/dashboard/'
    | '/notificacoes'
    | '/top-creator'
    | '/vitrine-de-campanhas'
    | '/dashboard-marca/criar-campanha'
    | '/dashboard/campanhas'
    | '/dashboard/chat'
    | '/dashboard/criar'
    | '/dashboard/campanhas/$campaignId/aplicar'
    | '/dashboard/campanhas/$campaignId/aprovar'
    | '/dashboard/campanhas/$campaignId/editar'
    | '/creator/$username'
    | '/marca/$userName'
    | '/dashboard/campanhas/$campaignId'
    | '/creator/$username/editar'
    | '/marca/$userName/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contrato-campanha'
    | '/privacidade'
    | '/termos'
    | '/cadastro/creator'
    | '/cadastro/marca'
    | '/cadastro'
    | '/esquecer-senha'
    | '/login123new'
    | '/dashboard'
    | '/dashboard-creator'
    | '/dashboard-marca'
    | '/notificacoes'
    | '/top-creator'
    | '/vitrine-de-campanhas'
    | '/dashboard-marca/criar-campanha'
    | '/dashboard/campanhas'
    | '/dashboard/chat'
    | '/dashboard/criar'
    | '/dashboard/campanhas/$campaignId/aplicar'
    | '/dashboard/campanhas/$campaignId/aprovar'
    | '/dashboard/campanhas/$campaignId/editar'
    | '/creator/$username'
    | '/marca/$userName'
    | '/dashboard/campanhas/$campaignId'
    | '/creator/$username/editar'
    | '/marca/$userName/editar'
  id:
    | '__root__'
    | '/'
    | '/_side-nav-dashboard'
    | '/contrato-campanha/'
    | '/privacidade/'
    | '/termos/'
    | '/cadastro/creator'
    | '/cadastro/marca'
    | '/cadastro/'
    | '/esquecer-senha/'
    | '/login123new/'
    | '/_side-nav-dashboard/dashboard'
    | '/_side-nav-dashboard/dashboard/_layout'
    | '/_side-nav-dashboard/dashboard-creator/'
    | '/_side-nav-dashboard/dashboard-marca/'
    | '/_side-nav-dashboard/dashboard/'
    | '/_side-nav-dashboard/notificacoes/'
    | '/_side-nav-dashboard/top-creator/'
    | '/_side-nav-dashboard/vitrine-de-campanhas/'
    | '/_side-nav-dashboard/dashboard-marca/criar-campanha/'
    | '/_side-nav-dashboard/dashboard/campanhas/'
    | '/_side-nav-dashboard/dashboard/chat/'
    | '/_side-nav-dashboard/dashboard/criar/'
    | '/_side-nav-dashboard/dashboard/campanhas/$campaignId/aplicar'
    | '/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar'
    | '/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar'
    | '/_side-nav-dashboard/creator/$username/'
    | '/_side-nav-dashboard/marca/$userName/'
    | '/_side-nav-dashboard/dashboard/campanhas/$campaignId/'
    | '/_side-nav-dashboard/creator/$username/editar/'
    | '/_side-nav-dashboard/marca/$userName/editar/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  dashboardRoute: typeof dashboardRouteWithChildren
  ContratoCampanhaIndexRoute: typeof ContratoCampanhaIndexRoute
  PrivacidadeIndexRoute: typeof PrivacidadeIndexRoute
  TermosIndexRoute: typeof TermosIndexRoute
  authCadastroCreatorRoute: typeof authCadastroCreatorRoute
  authCadastroMarcaRoute: typeof authCadastroMarcaRoute
  authCadastroIndexRoute: typeof authCadastroIndexRoute
  authEsquecerSenhaIndexRoute: typeof authEsquecerSenhaIndexRoute
  authLogin123newIndexRoute: typeof authLogin123newIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  dashboardRoute: dashboardRouteWithChildren,
  ContratoCampanhaIndexRoute: ContratoCampanhaIndexRoute,
  PrivacidadeIndexRoute: PrivacidadeIndexRoute,
  TermosIndexRoute: TermosIndexRoute,
  authCadastroCreatorRoute: authCadastroCreatorRoute,
  authCadastroMarcaRoute: authCadastroMarcaRoute,
  authCadastroIndexRoute: authCadastroIndexRoute,
  authEsquecerSenhaIndexRoute: authEsquecerSenhaIndexRoute,
  authLogin123newIndexRoute: authLogin123newIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/",
        "/contrato-campanha/",
        "/privacidade/",
        "/termos/",
        "/cadastro/creator",
        "/cadastro/marca",
        "/cadastro/",
        "/esquecer-senha/",
        "/login123new/"
      ]
    },
    "/": {
      "filePath": "(dashboard)",
      "children": [
        "/_side-nav-dashboard"
      ]
    },
    "/_side-nav-dashboard": {
      "filePath": "(dashboard)/_side-nav-dashboard.tsx",
      "parent": "/",
      "children": [
        "/_side-nav-dashboard/dashboard",
        "/_side-nav-dashboard/dashboard-creator/",
        "/_side-nav-dashboard/dashboard-marca/",
        "/_side-nav-dashboard/notificacoes/",
        "/_side-nav-dashboard/top-creator/",
        "/_side-nav-dashboard/vitrine-de-campanhas/",
        "/_side-nav-dashboard/dashboard-marca/criar-campanha/",
        "/_side-nav-dashboard/creator/$username/",
        "/_side-nav-dashboard/marca/$userName/",
        "/_side-nav-dashboard/creator/$username/editar/",
        "/_side-nav-dashboard/marca/$userName/editar/"
      ]
    },
    "/contrato-campanha/": {
      "filePath": "contrato-campanha/index.tsx"
    },
    "/privacidade/": {
      "filePath": "privacidade/index.tsx"
    },
    "/termos/": {
      "filePath": "termos/index.tsx"
    },
    "/cadastro/creator": {
      "filePath": "(auth)/cadastro/creator.tsx"
    },
    "/cadastro/marca": {
      "filePath": "(auth)/cadastro/marca.tsx"
    },
    "/cadastro/": {
      "filePath": "(auth)/cadastro/index.tsx"
    },
    "/esquecer-senha/": {
      "filePath": "(auth)/esquecer-senha/index.tsx"
    },
    "/login123new/": {
      "filePath": "(auth)/login123new/index.tsx"
    },
    "/_side-nav-dashboard/dashboard": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard",
      "parent": "/_side-nav-dashboard",
      "children": [
        "/_side-nav-dashboard/dashboard/_layout",
        "/_side-nav-dashboard/dashboard/",
        "/_side-nav-dashboard/dashboard/campanhas/",
        "/_side-nav-dashboard/dashboard/chat/",
        "/_side-nav-dashboard/dashboard/criar/",
        "/_side-nav-dashboard/dashboard/campanhas/$campaignId/aplicar",
        "/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar",
        "/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar",
        "/_side-nav-dashboard/dashboard/campanhas/$campaignId/"
      ]
    },
    "/_side-nav-dashboard/dashboard/_layout": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/_layout.tsx",
      "parent": "/_side-nav-dashboard/dashboard"
    },
    "/_side-nav-dashboard/dashboard-creator/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard-creator/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard-marca/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard-marca/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/index.tsx",
      "parent": "/_side-nav-dashboard/dashboard"
    },
    "/_side-nav-dashboard/notificacoes/": {
      "filePath": "(dashboard)/_side-nav-dashboard/notificacoes/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/top-creator/": {
      "filePath": "(dashboard)/_side-nav-dashboard/top-creator/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/vitrine-de-campanhas/": {
      "filePath": "(dashboard)/_side-nav-dashboard/vitrine-de-campanhas/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard-marca/criar-campanha/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard-marca/criar-campanha/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard/campanhas/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/campanhas/index.tsx",
      "parent": "/_side-nav-dashboard/dashboard"
    },
    "/_side-nav-dashboard/dashboard/chat/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/chat/index.tsx",
      "parent": "/_side-nav-dashboard/dashboard"
    },
    "/_side-nav-dashboard/dashboard/criar/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/criar/index.tsx",
      "parent": "/_side-nav-dashboard/dashboard"
    },
    "/_side-nav-dashboard/dashboard/campanhas/$campaignId/aplicar": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/aplicar.tsx",
      "parent": "/_side-nav-dashboard/dashboard"
    },
    "/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar.tsx",
      "parent": "/_side-nav-dashboard/dashboard"
    },
    "/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar.tsx",
      "parent": "/_side-nav-dashboard/dashboard"
    },
    "/_side-nav-dashboard/creator/$username/": {
      "filePath": "(dashboard)/_side-nav-dashboard/(perfis)/creator/$username/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/marca/$userName/": {
      "filePath": "(dashboard)/_side-nav-dashboard/(perfis)/marca/$userName/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard/campanhas/$campaignId/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/index.tsx",
      "parent": "/_side-nav-dashboard/dashboard"
    },
    "/_side-nav-dashboard/creator/$username/editar/": {
      "filePath": "(dashboard)/_side-nav-dashboard/(perfis)/creator/$username/editar/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/marca/$userName/editar/": {
      "filePath": "(dashboard)/_side-nav-dashboard/(perfis)/marca/$userName/editar/index.tsx",
      "parent": "/_side-nav-dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
