/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermosIndexImport } from './routes/termos/index'
import { Route as PrivacidadeIndexImport } from './routes/privacidade/index'
import { Route as ContratoCampanhaIndexImport } from './routes/contrato-campanha/index'
import { Route as dashboardSideNavDashboardImport } from './routes/(dashboard)/_side-nav-dashboard'
import { Route as authLoginIndexImport } from './routes/(auth)/login/index'
import { Route as authEsquecerSenhaIndexImport } from './routes/(auth)/esquecer-senha/index'
import { Route as authCadastroIndexImport } from './routes/(auth)/cadastro/index'
import { Route as authCadastroMarcaImport } from './routes/(auth)/cadastro/marca'
import { Route as authCadastroCreatorImport } from './routes/(auth)/cadastro/creator'
import { Route as dashboardSideNavDashboardVitrineDeCreatorsIndexImport } from './routes/(dashboard)/_side-nav-dashboard/vitrine-de-creators/index'
import { Route as dashboardSideNavDashboardVitrineDeCampanhasIndexImport } from './routes/(dashboard)/_side-nav-dashboard/vitrine-de-campanhas/index'
import { Route as dashboardSideNavDashboardTopCreatorIndexImport } from './routes/(dashboard)/_side-nav-dashboard/top-creator/index'
import { Route as dashboardSideNavDashboardNotificacoesIndexImport } from './routes/(dashboard)/_side-nav-dashboard/notificacoes/index'
import { Route as dashboardSideNavDashboardDashboardIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/index'
import { Route as dashboardSideNavDashboardDashboardMarcaIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard-marca/index'
import { Route as dashboardSideNavDashboardDashboardCreatorIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard-creator/index'
import { Route as dashboardSideNavDashboardCarteiraMarcaIndexImport } from './routes/(dashboard)/_side-nav-dashboard/carteira-marca/index'
import { Route as dashboardSideNavDashboardCarteiraCreatorIndexImport } from './routes/(dashboard)/_side-nav-dashboard/carteira-creator/index'
import { Route as recibosReciboMarcaCampanhaCampaignIdIndexImport } from './routes/(recibos)/recibo-marca/campanha/$campaignId/index'
import { Route as recibosReciboCreatorCampanhaCampaignIdIndexImport } from './routes/(recibos)/recibo-creator/campanha/$campaignId/index'
import { Route as dashboardSideNavDashboardRecursosMarcaIndexImport } from './routes/(dashboard)/_side-nav-dashboard/recursos/marca/index'
import { Route as dashboardSideNavDashboardRecursosCreatorIndexImport } from './routes/(dashboard)/_side-nav-dashboard/recursos/creator/index'
import { Route as dashboardSideNavDashboardPremiumMarcaIndexImport } from './routes/(dashboard)/_side-nav-dashboard/premium/marca/index'
import { Route as dashboardSideNavDashboardPremiumEbooksIndexImport } from './routes/(dashboard)/_side-nav-dashboard/premium/ebooks/index'
import { Route as dashboardSideNavDashboardPremiumCreatorIndexImport } from './routes/(dashboard)/_side-nav-dashboard/premium/creator/index'
import { Route as dashboardSideNavDashboardEntregaveisContratoIndexImport } from './routes/(dashboard)/_side-nav-dashboard/entregaveis/contrato/index'
import { Route as dashboardSideNavDashboardEntregaveisIdIndexImport } from './routes/(dashboard)/_side-nav-dashboard/entregaveis/$id/index'
import { Route as dashboardSideNavDashboardDashboardChatIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/chat/index'
import { Route as dashboardSideNavDashboardDashboardMarcaRascunhosIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard-marca/rascunhos/index'
import { Route as dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard-marca/criar-campanha/index'
import { Route as recibosReciboMarcaCreatorCreatorIdCampaignIdIndexImport } from './routes/(recibos)/recibo-marca/creator/$creatorId/$campaignId/index'
import { Route as dashboardSideNavDashboardPremiumCreatorConteudosIndexImport } from './routes/(dashboard)/_side-nav-dashboard/premium/creator/conteudos/index'
import { Route as dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/index'
import { Route as dashboardSideNavDashboardperfisMarcaUserNameIndexImport } from './routes/(dashboard)/_side-nav-dashboard/(perfis)/marca/$userName/index'
import { Route as dashboardSideNavDashboardperfisCreatorUsernameIndexImport } from './routes/(dashboard)/_side-nav-dashboard/(perfis)/creator/$username/index'
import { Route as dashboardSideNavDashboardDashboardCampanhasCampaignIdStatusImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/status'
import { Route as dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar'
import { Route as dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarImport } from './routes/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar'
import { Route as dashboardSideNavDashboardperfisMarcaUserNameEditarIndexImport } from './routes/(dashboard)/_side-nav-dashboard/(perfis)/marca/$userName/editar/index'
import { Route as dashboardSideNavDashboardperfisCreatorUsernameEditarIndexImport } from './routes/(dashboard)/_side-nav-dashboard/(perfis)/creator/$username/editar/index'

// Create Virtual Routes

const dashboardImport = createFileRoute('/(dashboard)')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const dashboardRoute = dashboardImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TermosIndexRoute = TermosIndexImport.update({
  path: '/termos/',
  getParentRoute: () => rootRoute,
} as any)

const PrivacidadeIndexRoute = PrivacidadeIndexImport.update({
  path: '/privacidade/',
  getParentRoute: () => rootRoute,
} as any)

const ContratoCampanhaIndexRoute = ContratoCampanhaIndexImport.update({
  path: '/contrato-campanha/',
  getParentRoute: () => rootRoute,
} as any)

const dashboardSideNavDashboardRoute = dashboardSideNavDashboardImport.update({
  id: '/_side-nav-dashboard',
  getParentRoute: () => dashboardRoute,
} as any)

const authLoginIndexRoute = authLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const authEsquecerSenhaIndexRoute = authEsquecerSenhaIndexImport.update({
  path: '/esquecer-senha/',
  getParentRoute: () => rootRoute,
} as any)

const authCadastroIndexRoute = authCadastroIndexImport.update({
  path: '/cadastro/',
  getParentRoute: () => rootRoute,
} as any)

const authCadastroMarcaRoute = authCadastroMarcaImport.update({
  path: '/cadastro/marca',
  getParentRoute: () => rootRoute,
} as any)

const authCadastroCreatorRoute = authCadastroCreatorImport.update({
  path: '/cadastro/creator',
  getParentRoute: () => rootRoute,
} as any)

const dashboardSideNavDashboardVitrineDeCreatorsIndexRoute =
  dashboardSideNavDashboardVitrineDeCreatorsIndexImport.update({
    path: '/vitrine-de-creators/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardVitrineDeCampanhasIndexRoute =
  dashboardSideNavDashboardVitrineDeCampanhasIndexImport.update({
    path: '/vitrine-de-campanhas/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardTopCreatorIndexRoute =
  dashboardSideNavDashboardTopCreatorIndexImport.update({
    path: '/top-creator/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardNotificacoesIndexRoute =
  dashboardSideNavDashboardNotificacoesIndexImport.update({
    path: '/notificacoes/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardIndexRoute =
  dashboardSideNavDashboardDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardMarcaIndexRoute =
  dashboardSideNavDashboardDashboardMarcaIndexImport.update({
    path: '/dashboard-marca/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardCreatorIndexRoute =
  dashboardSideNavDashboardDashboardCreatorIndexImport.update({
    path: '/dashboard-creator/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardCarteiraMarcaIndexRoute =
  dashboardSideNavDashboardCarteiraMarcaIndexImport.update({
    path: '/carteira-marca/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardCarteiraCreatorIndexRoute =
  dashboardSideNavDashboardCarteiraCreatorIndexImport.update({
    path: '/carteira-creator/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const recibosReciboMarcaCampanhaCampaignIdIndexRoute =
  recibosReciboMarcaCampanhaCampaignIdIndexImport.update({
    path: '/recibo-marca/campanha/$campaignId/',
    getParentRoute: () => rootRoute,
  } as any)

const recibosReciboCreatorCampanhaCampaignIdIndexRoute =
  recibosReciboCreatorCampanhaCampaignIdIndexImport.update({
    path: '/recibo-creator/campanha/$campaignId/',
    getParentRoute: () => rootRoute,
  } as any)

const dashboardSideNavDashboardRecursosMarcaIndexRoute =
  dashboardSideNavDashboardRecursosMarcaIndexImport.update({
    path: '/recursos/marca/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardRecursosCreatorIndexRoute =
  dashboardSideNavDashboardRecursosCreatorIndexImport.update({
    path: '/recursos/creator/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardPremiumMarcaIndexRoute =
  dashboardSideNavDashboardPremiumMarcaIndexImport.update({
    path: '/premium/marca/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardPremiumEbooksIndexRoute =
  dashboardSideNavDashboardPremiumEbooksIndexImport.update({
    path: '/premium/ebooks/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardPremiumCreatorIndexRoute =
  dashboardSideNavDashboardPremiumCreatorIndexImport.update({
    path: '/premium/creator/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardEntregaveisContratoIndexRoute =
  dashboardSideNavDashboardEntregaveisContratoIndexImport.update({
    path: '/entregaveis/contrato/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardEntregaveisIdIndexRoute =
  dashboardSideNavDashboardEntregaveisIdIndexImport.update({
    path: '/entregaveis/$id/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardChatIndexRoute =
  dashboardSideNavDashboardDashboardChatIndexImport.update({
    path: '/dashboard/chat/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardMarcaRascunhosIndexRoute =
  dashboardSideNavDashboardDashboardMarcaRascunhosIndexImport.update({
    path: '/dashboard-marca/rascunhos/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute =
  dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexImport.update({
    path: '/dashboard-marca/criar-campanha/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const recibosReciboMarcaCreatorCreatorIdCampaignIdIndexRoute =
  recibosReciboMarcaCreatorCreatorIdCampaignIdIndexImport.update({
    path: '/recibo-marca/creator/$creatorId/$campaignId/',
    getParentRoute: () => rootRoute,
  } as any)

const dashboardSideNavDashboardPremiumCreatorConteudosIndexRoute =
  dashboardSideNavDashboardPremiumCreatorConteudosIndexImport.update({
    path: '/premium/creator/conteudos/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute =
  dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexImport.update({
    path: '/dashboard/campanhas/$campaignId/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardperfisMarcaUserNameIndexRoute =
  dashboardSideNavDashboardperfisMarcaUserNameIndexImport.update({
    path: '/marca/$userName/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardperfisCreatorUsernameIndexRoute =
  dashboardSideNavDashboardperfisCreatorUsernameIndexImport.update({
    path: '/creator/$username/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardCampanhasCampaignIdStatusRoute =
  dashboardSideNavDashboardDashboardCampanhasCampaignIdStatusImport.update({
    path: '/dashboard/campanhas/$campaignId/status',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute =
  dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarImport.update({
    path: '/dashboard/campanhas/$campaignId/editar',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute =
  dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarImport.update({
    path: '/dashboard/campanhas/$campaignId/aprovar',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute =
  dashboardSideNavDashboardperfisMarcaUserNameEditarIndexImport.update({
    path: '/marca/$userName/editar/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

const dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute =
  dashboardSideNavDashboardperfisCreatorUsernameEditarIndexImport.update({
    path: '/creator/$username/editar/',
    getParentRoute: () => dashboardSideNavDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/_side-nav-dashboard': {
      id: '/_side-nav-dashboard'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardSideNavDashboardImport
      parentRoute: typeof dashboardRoute
    }
    '/contrato-campanha/': {
      id: '/contrato-campanha/'
      path: '/contrato-campanha'
      fullPath: '/contrato-campanha'
      preLoaderRoute: typeof ContratoCampanhaIndexImport
      parentRoute: typeof rootRoute
    }
    '/privacidade/': {
      id: '/privacidade/'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeIndexImport
      parentRoute: typeof rootRoute
    }
    '/termos/': {
      id: '/termos/'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/cadastro/creator': {
      id: '/cadastro/creator'
      path: '/cadastro/creator'
      fullPath: '/cadastro/creator'
      preLoaderRoute: typeof authCadastroCreatorImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/cadastro/marca': {
      id: '/cadastro/marca'
      path: '/cadastro/marca'
      fullPath: '/cadastro/marca'
      preLoaderRoute: typeof authCadastroMarcaImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/cadastro/': {
      id: '/cadastro/'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof authCadastroIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/esquecer-senha/': {
      id: '/esquecer-senha/'
      path: '/esquecer-senha'
      fullPath: '/esquecer-senha'
      preLoaderRoute: typeof authEsquecerSenhaIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/_side-nav-dashboard/carteira-creator/': {
      id: '/_side-nav-dashboard/carteira-creator/'
      path: '/carteira-creator'
      fullPath: '/carteira-creator'
      preLoaderRoute: typeof dashboardSideNavDashboardCarteiraCreatorIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/carteira-marca/': {
      id: '/_side-nav-dashboard/carteira-marca/'
      path: '/carteira-marca'
      fullPath: '/carteira-marca'
      preLoaderRoute: typeof dashboardSideNavDashboardCarteiraMarcaIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard-creator/': {
      id: '/_side-nav-dashboard/dashboard-creator/'
      path: '/dashboard-creator'
      fullPath: '/dashboard-creator'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardCreatorIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard-marca/': {
      id: '/_side-nav-dashboard/dashboard-marca/'
      path: '/dashboard-marca'
      fullPath: '/dashboard-marca'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardMarcaIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/': {
      id: '/_side-nav-dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/notificacoes/': {
      id: '/_side-nav-dashboard/notificacoes/'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof dashboardSideNavDashboardNotificacoesIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/top-creator/': {
      id: '/_side-nav-dashboard/top-creator/'
      path: '/top-creator'
      fullPath: '/top-creator'
      preLoaderRoute: typeof dashboardSideNavDashboardTopCreatorIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/vitrine-de-campanhas/': {
      id: '/_side-nav-dashboard/vitrine-de-campanhas/'
      path: '/vitrine-de-campanhas'
      fullPath: '/vitrine-de-campanhas'
      preLoaderRoute: typeof dashboardSideNavDashboardVitrineDeCampanhasIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/vitrine-de-creators/': {
      id: '/_side-nav-dashboard/vitrine-de-creators/'
      path: '/vitrine-de-creators'
      fullPath: '/vitrine-de-creators'
      preLoaderRoute: typeof dashboardSideNavDashboardVitrineDeCreatorsIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard-marca/criar-campanha/': {
      id: '/_side-nav-dashboard/dashboard-marca/criar-campanha/'
      path: '/dashboard-marca/criar-campanha'
      fullPath: '/dashboard-marca/criar-campanha'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard-marca/rascunhos/': {
      id: '/_side-nav-dashboard/dashboard-marca/rascunhos/'
      path: '/dashboard-marca/rascunhos'
      fullPath: '/dashboard-marca/rascunhos'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardMarcaRascunhosIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/chat/': {
      id: '/_side-nav-dashboard/dashboard/chat/'
      path: '/dashboard/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardChatIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/entregaveis/$id/': {
      id: '/_side-nav-dashboard/entregaveis/$id/'
      path: '/entregaveis/$id'
      fullPath: '/entregaveis/$id'
      preLoaderRoute: typeof dashboardSideNavDashboardEntregaveisIdIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/entregaveis/contrato/': {
      id: '/_side-nav-dashboard/entregaveis/contrato/'
      path: '/entregaveis/contrato'
      fullPath: '/entregaveis/contrato'
      preLoaderRoute: typeof dashboardSideNavDashboardEntregaveisContratoIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/premium/creator/': {
      id: '/_side-nav-dashboard/premium/creator/'
      path: '/premium/creator'
      fullPath: '/premium/creator'
      preLoaderRoute: typeof dashboardSideNavDashboardPremiumCreatorIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/premium/ebooks/': {
      id: '/_side-nav-dashboard/premium/ebooks/'
      path: '/premium/ebooks'
      fullPath: '/premium/ebooks'
      preLoaderRoute: typeof dashboardSideNavDashboardPremiumEbooksIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/premium/marca/': {
      id: '/_side-nav-dashboard/premium/marca/'
      path: '/premium/marca'
      fullPath: '/premium/marca'
      preLoaderRoute: typeof dashboardSideNavDashboardPremiumMarcaIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/recursos/creator/': {
      id: '/_side-nav-dashboard/recursos/creator/'
      path: '/recursos/creator'
      fullPath: '/recursos/creator'
      preLoaderRoute: typeof dashboardSideNavDashboardRecursosCreatorIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/recursos/marca/': {
      id: '/_side-nav-dashboard/recursos/marca/'
      path: '/recursos/marca'
      fullPath: '/recursos/marca'
      preLoaderRoute: typeof dashboardSideNavDashboardRecursosMarcaIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(recibos)/recibo-creator/campanha/$campaignId/': {
      id: '/recibo-creator/campanha/$campaignId/'
      path: '/recibo-creator/campanha/$campaignId'
      fullPath: '/recibo-creator/campanha/$campaignId'
      preLoaderRoute: typeof recibosReciboCreatorCampanhaCampaignIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/(recibos)/recibo-marca/campanha/$campaignId/': {
      id: '/recibo-marca/campanha/$campaignId/'
      path: '/recibo-marca/campanha/$campaignId'
      fullPath: '/recibo-marca/campanha/$campaignId'
      preLoaderRoute: typeof recibosReciboMarcaCampanhaCampaignIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar': {
      id: '/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar'
      path: '/dashboard/campanhas/$campaignId/aprovar'
      fullPath: '/dashboard/campanhas/$campaignId/aprovar'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar': {
      id: '/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar'
      path: '/dashboard/campanhas/$campaignId/editar'
      fullPath: '/dashboard/campanhas/$campaignId/editar'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/status': {
      id: '/_side-nav-dashboard/dashboard/campanhas/$campaignId/status'
      path: '/dashboard/campanhas/$campaignId/status'
      fullPath: '/dashboard/campanhas/$campaignId/status'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdStatusImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/(perfis)/creator/$username/': {
      id: '/_side-nav-dashboard/creator/$username/'
      path: '/creator/$username'
      fullPath: '/creator/$username'
      preLoaderRoute: typeof dashboardSideNavDashboardperfisCreatorUsernameIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/(perfis)/marca/$userName/': {
      id: '/_side-nav-dashboard/marca/$userName/'
      path: '/marca/$userName'
      fullPath: '/marca/$userName'
      preLoaderRoute: typeof dashboardSideNavDashboardperfisMarcaUserNameIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/': {
      id: '/_side-nav-dashboard/dashboard/campanhas/$campaignId/'
      path: '/dashboard/campanhas/$campaignId'
      fullPath: '/dashboard/campanhas/$campaignId'
      preLoaderRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/premium/creator/conteudos/': {
      id: '/_side-nav-dashboard/premium/creator/conteudos/'
      path: '/premium/creator/conteudos'
      fullPath: '/premium/creator/conteudos'
      preLoaderRoute: typeof dashboardSideNavDashboardPremiumCreatorConteudosIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(recibos)/recibo-marca/creator/$creatorId/$campaignId/': {
      id: '/recibo-marca/creator/$creatorId/$campaignId/'
      path: '/recibo-marca/creator/$creatorId/$campaignId'
      fullPath: '/recibo-marca/creator/$creatorId/$campaignId'
      preLoaderRoute: typeof recibosReciboMarcaCreatorCreatorIdCampaignIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/_side-nav-dashboard/(perfis)/creator/$username/editar/': {
      id: '/_side-nav-dashboard/creator/$username/editar/'
      path: '/creator/$username/editar'
      fullPath: '/creator/$username/editar'
      preLoaderRoute: typeof dashboardSideNavDashboardperfisCreatorUsernameEditarIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
    '/(dashboard)/_side-nav-dashboard/(perfis)/marca/$userName/editar/': {
      id: '/_side-nav-dashboard/marca/$userName/editar/'
      path: '/marca/$userName/editar'
      fullPath: '/marca/$userName/editar'
      preLoaderRoute: typeof dashboardSideNavDashboardperfisMarcaUserNameEditarIndexImport
      parentRoute: typeof dashboardSideNavDashboardImport
    }
  }
}

// Create and export the route tree

interface dashboardSideNavDashboardRouteChildren {
  dashboardSideNavDashboardCarteiraCreatorIndexRoute: typeof dashboardSideNavDashboardCarteiraCreatorIndexRoute
  dashboardSideNavDashboardCarteiraMarcaIndexRoute: typeof dashboardSideNavDashboardCarteiraMarcaIndexRoute
  dashboardSideNavDashboardDashboardCreatorIndexRoute: typeof dashboardSideNavDashboardDashboardCreatorIndexRoute
  dashboardSideNavDashboardDashboardMarcaIndexRoute: typeof dashboardSideNavDashboardDashboardMarcaIndexRoute
  dashboardSideNavDashboardDashboardIndexRoute: typeof dashboardSideNavDashboardDashboardIndexRoute
  dashboardSideNavDashboardNotificacoesIndexRoute: typeof dashboardSideNavDashboardNotificacoesIndexRoute
  dashboardSideNavDashboardTopCreatorIndexRoute: typeof dashboardSideNavDashboardTopCreatorIndexRoute
  dashboardSideNavDashboardVitrineDeCampanhasIndexRoute: typeof dashboardSideNavDashboardVitrineDeCampanhasIndexRoute
  dashboardSideNavDashboardVitrineDeCreatorsIndexRoute: typeof dashboardSideNavDashboardVitrineDeCreatorsIndexRoute
  dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute: typeof dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute
  dashboardSideNavDashboardDashboardMarcaRascunhosIndexRoute: typeof dashboardSideNavDashboardDashboardMarcaRascunhosIndexRoute
  dashboardSideNavDashboardDashboardChatIndexRoute: typeof dashboardSideNavDashboardDashboardChatIndexRoute
  dashboardSideNavDashboardEntregaveisIdIndexRoute: typeof dashboardSideNavDashboardEntregaveisIdIndexRoute
  dashboardSideNavDashboardEntregaveisContratoIndexRoute: typeof dashboardSideNavDashboardEntregaveisContratoIndexRoute
  dashboardSideNavDashboardPremiumCreatorIndexRoute: typeof dashboardSideNavDashboardPremiumCreatorIndexRoute
  dashboardSideNavDashboardPremiumEbooksIndexRoute: typeof dashboardSideNavDashboardPremiumEbooksIndexRoute
  dashboardSideNavDashboardPremiumMarcaIndexRoute: typeof dashboardSideNavDashboardPremiumMarcaIndexRoute
  dashboardSideNavDashboardRecursosCreatorIndexRoute: typeof dashboardSideNavDashboardRecursosCreatorIndexRoute
  dashboardSideNavDashboardRecursosMarcaIndexRoute: typeof dashboardSideNavDashboardRecursosMarcaIndexRoute
  dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute
  dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute
  dashboardSideNavDashboardDashboardCampanhasCampaignIdStatusRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdStatusRoute
  dashboardSideNavDashboardperfisCreatorUsernameIndexRoute: typeof dashboardSideNavDashboardperfisCreatorUsernameIndexRoute
  dashboardSideNavDashboardperfisMarcaUserNameIndexRoute: typeof dashboardSideNavDashboardperfisMarcaUserNameIndexRoute
  dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute: typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute
  dashboardSideNavDashboardPremiumCreatorConteudosIndexRoute: typeof dashboardSideNavDashboardPremiumCreatorConteudosIndexRoute
  dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute: typeof dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute
  dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute: typeof dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute
}

const dashboardSideNavDashboardRouteChildren: dashboardSideNavDashboardRouteChildren =
  {
    dashboardSideNavDashboardCarteiraCreatorIndexRoute:
      dashboardSideNavDashboardCarteiraCreatorIndexRoute,
    dashboardSideNavDashboardCarteiraMarcaIndexRoute:
      dashboardSideNavDashboardCarteiraMarcaIndexRoute,
    dashboardSideNavDashboardDashboardCreatorIndexRoute:
      dashboardSideNavDashboardDashboardCreatorIndexRoute,
    dashboardSideNavDashboardDashboardMarcaIndexRoute:
      dashboardSideNavDashboardDashboardMarcaIndexRoute,
    dashboardSideNavDashboardDashboardIndexRoute:
      dashboardSideNavDashboardDashboardIndexRoute,
    dashboardSideNavDashboardNotificacoesIndexRoute:
      dashboardSideNavDashboardNotificacoesIndexRoute,
    dashboardSideNavDashboardTopCreatorIndexRoute:
      dashboardSideNavDashboardTopCreatorIndexRoute,
    dashboardSideNavDashboardVitrineDeCampanhasIndexRoute:
      dashboardSideNavDashboardVitrineDeCampanhasIndexRoute,
    dashboardSideNavDashboardVitrineDeCreatorsIndexRoute:
      dashboardSideNavDashboardVitrineDeCreatorsIndexRoute,
    dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute:
      dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute,
    dashboardSideNavDashboardDashboardMarcaRascunhosIndexRoute:
      dashboardSideNavDashboardDashboardMarcaRascunhosIndexRoute,
    dashboardSideNavDashboardDashboardChatIndexRoute:
      dashboardSideNavDashboardDashboardChatIndexRoute,
    dashboardSideNavDashboardEntregaveisIdIndexRoute:
      dashboardSideNavDashboardEntregaveisIdIndexRoute,
    dashboardSideNavDashboardEntregaveisContratoIndexRoute:
      dashboardSideNavDashboardEntregaveisContratoIndexRoute,
    dashboardSideNavDashboardPremiumCreatorIndexRoute:
      dashboardSideNavDashboardPremiumCreatorIndexRoute,
    dashboardSideNavDashboardPremiumEbooksIndexRoute:
      dashboardSideNavDashboardPremiumEbooksIndexRoute,
    dashboardSideNavDashboardPremiumMarcaIndexRoute:
      dashboardSideNavDashboardPremiumMarcaIndexRoute,
    dashboardSideNavDashboardRecursosCreatorIndexRoute:
      dashboardSideNavDashboardRecursosCreatorIndexRoute,
    dashboardSideNavDashboardRecursosMarcaIndexRoute:
      dashboardSideNavDashboardRecursosMarcaIndexRoute,
    dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute:
      dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute,
    dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute:
      dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute,
    dashboardSideNavDashboardDashboardCampanhasCampaignIdStatusRoute:
      dashboardSideNavDashboardDashboardCampanhasCampaignIdStatusRoute,
    dashboardSideNavDashboardperfisCreatorUsernameIndexRoute:
      dashboardSideNavDashboardperfisCreatorUsernameIndexRoute,
    dashboardSideNavDashboardperfisMarcaUserNameIndexRoute:
      dashboardSideNavDashboardperfisMarcaUserNameIndexRoute,
    dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute:
      dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute,
    dashboardSideNavDashboardPremiumCreatorConteudosIndexRoute:
      dashboardSideNavDashboardPremiumCreatorConteudosIndexRoute,
    dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute:
      dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute,
    dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute:
      dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute,
  }

const dashboardSideNavDashboardRouteWithChildren =
  dashboardSideNavDashboardRoute._addFileChildren(
    dashboardSideNavDashboardRouteChildren,
  )

interface dashboardRouteChildren {
  dashboardSideNavDashboardRoute: typeof dashboardSideNavDashboardRouteWithChildren
}

const dashboardRouteChildren: dashboardRouteChildren = {
  dashboardSideNavDashboardRoute: dashboardSideNavDashboardRouteWithChildren,
}

const dashboardRouteWithChildren = dashboardRoute._addFileChildren(
  dashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof dashboardSideNavDashboardRouteWithChildren
  '/contrato-campanha': typeof ContratoCampanhaIndexRoute
  '/privacidade': typeof PrivacidadeIndexRoute
  '/termos': typeof TermosIndexRoute
  '/cadastro/creator': typeof authCadastroCreatorRoute
  '/cadastro/marca': typeof authCadastroMarcaRoute
  '/cadastro': typeof authCadastroIndexRoute
  '/esquecer-senha': typeof authEsquecerSenhaIndexRoute
  '/login': typeof authLoginIndexRoute
  '/carteira-creator': typeof dashboardSideNavDashboardCarteiraCreatorIndexRoute
  '/carteira-marca': typeof dashboardSideNavDashboardCarteiraMarcaIndexRoute
  '/dashboard-creator': typeof dashboardSideNavDashboardDashboardCreatorIndexRoute
  '/dashboard-marca': typeof dashboardSideNavDashboardDashboardMarcaIndexRoute
  '/dashboard': typeof dashboardSideNavDashboardDashboardIndexRoute
  '/notificacoes': typeof dashboardSideNavDashboardNotificacoesIndexRoute
  '/top-creator': typeof dashboardSideNavDashboardTopCreatorIndexRoute
  '/vitrine-de-campanhas': typeof dashboardSideNavDashboardVitrineDeCampanhasIndexRoute
  '/vitrine-de-creators': typeof dashboardSideNavDashboardVitrineDeCreatorsIndexRoute
  '/dashboard-marca/criar-campanha': typeof dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute
  '/dashboard-marca/rascunhos': typeof dashboardSideNavDashboardDashboardMarcaRascunhosIndexRoute
  '/dashboard/chat': typeof dashboardSideNavDashboardDashboardChatIndexRoute
  '/entregaveis/$id': typeof dashboardSideNavDashboardEntregaveisIdIndexRoute
  '/entregaveis/contrato': typeof dashboardSideNavDashboardEntregaveisContratoIndexRoute
  '/premium/creator': typeof dashboardSideNavDashboardPremiumCreatorIndexRoute
  '/premium/ebooks': typeof dashboardSideNavDashboardPremiumEbooksIndexRoute
  '/premium/marca': typeof dashboardSideNavDashboardPremiumMarcaIndexRoute
  '/recursos/creator': typeof dashboardSideNavDashboardRecursosCreatorIndexRoute
  '/recursos/marca': typeof dashboardSideNavDashboardRecursosMarcaIndexRoute
  '/recibo-creator/campanha/$campaignId': typeof recibosReciboCreatorCampanhaCampaignIdIndexRoute
  '/recibo-marca/campanha/$campaignId': typeof recibosReciboMarcaCampanhaCampaignIdIndexRoute
  '/dashboard/campanhas/$campaignId/aprovar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute
  '/dashboard/campanhas/$campaignId/editar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute
  '/dashboard/campanhas/$campaignId/status': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdStatusRoute
  '/creator/$username': typeof dashboardSideNavDashboardperfisCreatorUsernameIndexRoute
  '/marca/$userName': typeof dashboardSideNavDashboardperfisMarcaUserNameIndexRoute
  '/dashboard/campanhas/$campaignId': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute
  '/premium/creator/conteudos': typeof dashboardSideNavDashboardPremiumCreatorConteudosIndexRoute
  '/recibo-marca/creator/$creatorId/$campaignId': typeof recibosReciboMarcaCreatorCreatorIdCampaignIdIndexRoute
  '/creator/$username/editar': typeof dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute
  '/marca/$userName/editar': typeof dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof dashboardSideNavDashboardRouteWithChildren
  '/contrato-campanha': typeof ContratoCampanhaIndexRoute
  '/privacidade': typeof PrivacidadeIndexRoute
  '/termos': typeof TermosIndexRoute
  '/cadastro/creator': typeof authCadastroCreatorRoute
  '/cadastro/marca': typeof authCadastroMarcaRoute
  '/cadastro': typeof authCadastroIndexRoute
  '/esquecer-senha': typeof authEsquecerSenhaIndexRoute
  '/login': typeof authLoginIndexRoute
  '/carteira-creator': typeof dashboardSideNavDashboardCarteiraCreatorIndexRoute
  '/carteira-marca': typeof dashboardSideNavDashboardCarteiraMarcaIndexRoute
  '/dashboard-creator': typeof dashboardSideNavDashboardDashboardCreatorIndexRoute
  '/dashboard-marca': typeof dashboardSideNavDashboardDashboardMarcaIndexRoute
  '/dashboard': typeof dashboardSideNavDashboardDashboardIndexRoute
  '/notificacoes': typeof dashboardSideNavDashboardNotificacoesIndexRoute
  '/top-creator': typeof dashboardSideNavDashboardTopCreatorIndexRoute
  '/vitrine-de-campanhas': typeof dashboardSideNavDashboardVitrineDeCampanhasIndexRoute
  '/vitrine-de-creators': typeof dashboardSideNavDashboardVitrineDeCreatorsIndexRoute
  '/dashboard-marca/criar-campanha': typeof dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute
  '/dashboard-marca/rascunhos': typeof dashboardSideNavDashboardDashboardMarcaRascunhosIndexRoute
  '/dashboard/chat': typeof dashboardSideNavDashboardDashboardChatIndexRoute
  '/entregaveis/$id': typeof dashboardSideNavDashboardEntregaveisIdIndexRoute
  '/entregaveis/contrato': typeof dashboardSideNavDashboardEntregaveisContratoIndexRoute
  '/premium/creator': typeof dashboardSideNavDashboardPremiumCreatorIndexRoute
  '/premium/ebooks': typeof dashboardSideNavDashboardPremiumEbooksIndexRoute
  '/premium/marca': typeof dashboardSideNavDashboardPremiumMarcaIndexRoute
  '/recursos/creator': typeof dashboardSideNavDashboardRecursosCreatorIndexRoute
  '/recursos/marca': typeof dashboardSideNavDashboardRecursosMarcaIndexRoute
  '/recibo-creator/campanha/$campaignId': typeof recibosReciboCreatorCampanhaCampaignIdIndexRoute
  '/recibo-marca/campanha/$campaignId': typeof recibosReciboMarcaCampanhaCampaignIdIndexRoute
  '/dashboard/campanhas/$campaignId/aprovar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute
  '/dashboard/campanhas/$campaignId/editar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute
  '/dashboard/campanhas/$campaignId/status': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdStatusRoute
  '/creator/$username': typeof dashboardSideNavDashboardperfisCreatorUsernameIndexRoute
  '/marca/$userName': typeof dashboardSideNavDashboardperfisMarcaUserNameIndexRoute
  '/dashboard/campanhas/$campaignId': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute
  '/premium/creator/conteudos': typeof dashboardSideNavDashboardPremiumCreatorConteudosIndexRoute
  '/recibo-marca/creator/$creatorId/$campaignId': typeof recibosReciboMarcaCreatorCreatorIdCampaignIdIndexRoute
  '/creator/$username/editar': typeof dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute
  '/marca/$userName/editar': typeof dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof dashboardRouteWithChildren
  '/_side-nav-dashboard': typeof dashboardSideNavDashboardRouteWithChildren
  '/contrato-campanha/': typeof ContratoCampanhaIndexRoute
  '/privacidade/': typeof PrivacidadeIndexRoute
  '/termos/': typeof TermosIndexRoute
  '/cadastro/creator': typeof authCadastroCreatorRoute
  '/cadastro/marca': typeof authCadastroMarcaRoute
  '/cadastro/': typeof authCadastroIndexRoute
  '/esquecer-senha/': typeof authEsquecerSenhaIndexRoute
  '/login/': typeof authLoginIndexRoute
  '/_side-nav-dashboard/carteira-creator/': typeof dashboardSideNavDashboardCarteiraCreatorIndexRoute
  '/_side-nav-dashboard/carteira-marca/': typeof dashboardSideNavDashboardCarteiraMarcaIndexRoute
  '/_side-nav-dashboard/dashboard-creator/': typeof dashboardSideNavDashboardDashboardCreatorIndexRoute
  '/_side-nav-dashboard/dashboard-marca/': typeof dashboardSideNavDashboardDashboardMarcaIndexRoute
  '/_side-nav-dashboard/dashboard/': typeof dashboardSideNavDashboardDashboardIndexRoute
  '/_side-nav-dashboard/notificacoes/': typeof dashboardSideNavDashboardNotificacoesIndexRoute
  '/_side-nav-dashboard/top-creator/': typeof dashboardSideNavDashboardTopCreatorIndexRoute
  '/_side-nav-dashboard/vitrine-de-campanhas/': typeof dashboardSideNavDashboardVitrineDeCampanhasIndexRoute
  '/_side-nav-dashboard/vitrine-de-creators/': typeof dashboardSideNavDashboardVitrineDeCreatorsIndexRoute
  '/_side-nav-dashboard/dashboard-marca/criar-campanha/': typeof dashboardSideNavDashboardDashboardMarcaCriarCampanhaIndexRoute
  '/_side-nav-dashboard/dashboard-marca/rascunhos/': typeof dashboardSideNavDashboardDashboardMarcaRascunhosIndexRoute
  '/_side-nav-dashboard/dashboard/chat/': typeof dashboardSideNavDashboardDashboardChatIndexRoute
  '/_side-nav-dashboard/entregaveis/$id/': typeof dashboardSideNavDashboardEntregaveisIdIndexRoute
  '/_side-nav-dashboard/entregaveis/contrato/': typeof dashboardSideNavDashboardEntregaveisContratoIndexRoute
  '/_side-nav-dashboard/premium/creator/': typeof dashboardSideNavDashboardPremiumCreatorIndexRoute
  '/_side-nav-dashboard/premium/ebooks/': typeof dashboardSideNavDashboardPremiumEbooksIndexRoute
  '/_side-nav-dashboard/premium/marca/': typeof dashboardSideNavDashboardPremiumMarcaIndexRoute
  '/_side-nav-dashboard/recursos/creator/': typeof dashboardSideNavDashboardRecursosCreatorIndexRoute
  '/_side-nav-dashboard/recursos/marca/': typeof dashboardSideNavDashboardRecursosMarcaIndexRoute
  '/recibo-creator/campanha/$campaignId/': typeof recibosReciboCreatorCampanhaCampaignIdIndexRoute
  '/recibo-marca/campanha/$campaignId/': typeof recibosReciboMarcaCampanhaCampaignIdIndexRoute
  '/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdAprovarRoute
  '/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdEditarRoute
  '/_side-nav-dashboard/dashboard/campanhas/$campaignId/status': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdStatusRoute
  '/_side-nav-dashboard/creator/$username/': typeof dashboardSideNavDashboardperfisCreatorUsernameIndexRoute
  '/_side-nav-dashboard/marca/$userName/': typeof dashboardSideNavDashboardperfisMarcaUserNameIndexRoute
  '/_side-nav-dashboard/dashboard/campanhas/$campaignId/': typeof dashboardSideNavDashboardDashboardCampanhasCampaignIdIndexRoute
  '/_side-nav-dashboard/premium/creator/conteudos/': typeof dashboardSideNavDashboardPremiumCreatorConteudosIndexRoute
  '/recibo-marca/creator/$creatorId/$campaignId/': typeof recibosReciboMarcaCreatorCreatorIdCampaignIdIndexRoute
  '/_side-nav-dashboard/creator/$username/editar/': typeof dashboardSideNavDashboardperfisCreatorUsernameEditarIndexRoute
  '/_side-nav-dashboard/marca/$userName/editar/': typeof dashboardSideNavDashboardperfisMarcaUserNameEditarIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contrato-campanha'
    | '/privacidade'
    | '/termos'
    | '/cadastro/creator'
    | '/cadastro/marca'
    | '/cadastro'
    | '/esquecer-senha'
    | '/login'
    | '/carteira-creator'
    | '/carteira-marca'
    | '/dashboard-creator'
    | '/dashboard-marca'
    | '/dashboard'
    | '/notificacoes'
    | '/top-creator'
    | '/vitrine-de-campanhas'
    | '/vitrine-de-creators'
    | '/dashboard-marca/criar-campanha'
    | '/dashboard-marca/rascunhos'
    | '/dashboard/chat'
    | '/entregaveis/$id'
    | '/entregaveis/contrato'
    | '/premium/creator'
    | '/premium/ebooks'
    | '/premium/marca'
    | '/recursos/creator'
    | '/recursos/marca'
    | '/recibo-creator/campanha/$campaignId'
    | '/recibo-marca/campanha/$campaignId'
    | '/dashboard/campanhas/$campaignId/aprovar'
    | '/dashboard/campanhas/$campaignId/editar'
    | '/dashboard/campanhas/$campaignId/status'
    | '/creator/$username'
    | '/marca/$userName'
    | '/dashboard/campanhas/$campaignId'
    | '/premium/creator/conteudos'
    | '/recibo-marca/creator/$creatorId/$campaignId'
    | '/creator/$username/editar'
    | '/marca/$userName/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contrato-campanha'
    | '/privacidade'
    | '/termos'
    | '/cadastro/creator'
    | '/cadastro/marca'
    | '/cadastro'
    | '/esquecer-senha'
    | '/login'
    | '/carteira-creator'
    | '/carteira-marca'
    | '/dashboard-creator'
    | '/dashboard-marca'
    | '/dashboard'
    | '/notificacoes'
    | '/top-creator'
    | '/vitrine-de-campanhas'
    | '/vitrine-de-creators'
    | '/dashboard-marca/criar-campanha'
    | '/dashboard-marca/rascunhos'
    | '/dashboard/chat'
    | '/entregaveis/$id'
    | '/entregaveis/contrato'
    | '/premium/creator'
    | '/premium/ebooks'
    | '/premium/marca'
    | '/recursos/creator'
    | '/recursos/marca'
    | '/recibo-creator/campanha/$campaignId'
    | '/recibo-marca/campanha/$campaignId'
    | '/dashboard/campanhas/$campaignId/aprovar'
    | '/dashboard/campanhas/$campaignId/editar'
    | '/dashboard/campanhas/$campaignId/status'
    | '/creator/$username'
    | '/marca/$userName'
    | '/dashboard/campanhas/$campaignId'
    | '/premium/creator/conteudos'
    | '/recibo-marca/creator/$creatorId/$campaignId'
    | '/creator/$username/editar'
    | '/marca/$userName/editar'
  id:
    | '__root__'
    | '/'
    | '/_side-nav-dashboard'
    | '/contrato-campanha/'
    | '/privacidade/'
    | '/termos/'
    | '/cadastro/creator'
    | '/cadastro/marca'
    | '/cadastro/'
    | '/esquecer-senha/'
    | '/login/'
    | '/_side-nav-dashboard/carteira-creator/'
    | '/_side-nav-dashboard/carteira-marca/'
    | '/_side-nav-dashboard/dashboard-creator/'
    | '/_side-nav-dashboard/dashboard-marca/'
    | '/_side-nav-dashboard/dashboard/'
    | '/_side-nav-dashboard/notificacoes/'
    | '/_side-nav-dashboard/top-creator/'
    | '/_side-nav-dashboard/vitrine-de-campanhas/'
    | '/_side-nav-dashboard/vitrine-de-creators/'
    | '/_side-nav-dashboard/dashboard-marca/criar-campanha/'
    | '/_side-nav-dashboard/dashboard-marca/rascunhos/'
    | '/_side-nav-dashboard/dashboard/chat/'
    | '/_side-nav-dashboard/entregaveis/$id/'
    | '/_side-nav-dashboard/entregaveis/contrato/'
    | '/_side-nav-dashboard/premium/creator/'
    | '/_side-nav-dashboard/premium/ebooks/'
    | '/_side-nav-dashboard/premium/marca/'
    | '/_side-nav-dashboard/recursos/creator/'
    | '/_side-nav-dashboard/recursos/marca/'
    | '/recibo-creator/campanha/$campaignId/'
    | '/recibo-marca/campanha/$campaignId/'
    | '/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar'
    | '/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar'
    | '/_side-nav-dashboard/dashboard/campanhas/$campaignId/status'
    | '/_side-nav-dashboard/creator/$username/'
    | '/_side-nav-dashboard/marca/$userName/'
    | '/_side-nav-dashboard/dashboard/campanhas/$campaignId/'
    | '/_side-nav-dashboard/premium/creator/conteudos/'
    | '/recibo-marca/creator/$creatorId/$campaignId/'
    | '/_side-nav-dashboard/creator/$username/editar/'
    | '/_side-nav-dashboard/marca/$userName/editar/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  dashboardRoute: typeof dashboardRouteWithChildren
  ContratoCampanhaIndexRoute: typeof ContratoCampanhaIndexRoute
  PrivacidadeIndexRoute: typeof PrivacidadeIndexRoute
  TermosIndexRoute: typeof TermosIndexRoute
  authCadastroCreatorRoute: typeof authCadastroCreatorRoute
  authCadastroMarcaRoute: typeof authCadastroMarcaRoute
  authCadastroIndexRoute: typeof authCadastroIndexRoute
  authEsquecerSenhaIndexRoute: typeof authEsquecerSenhaIndexRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  recibosReciboCreatorCampanhaCampaignIdIndexRoute: typeof recibosReciboCreatorCampanhaCampaignIdIndexRoute
  recibosReciboMarcaCampanhaCampaignIdIndexRoute: typeof recibosReciboMarcaCampanhaCampaignIdIndexRoute
  recibosReciboMarcaCreatorCreatorIdCampaignIdIndexRoute: typeof recibosReciboMarcaCreatorCreatorIdCampaignIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  dashboardRoute: dashboardRouteWithChildren,
  ContratoCampanhaIndexRoute: ContratoCampanhaIndexRoute,
  PrivacidadeIndexRoute: PrivacidadeIndexRoute,
  TermosIndexRoute: TermosIndexRoute,
  authCadastroCreatorRoute: authCadastroCreatorRoute,
  authCadastroMarcaRoute: authCadastroMarcaRoute,
  authCadastroIndexRoute: authCadastroIndexRoute,
  authEsquecerSenhaIndexRoute: authEsquecerSenhaIndexRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  recibosReciboCreatorCampanhaCampaignIdIndexRoute:
    recibosReciboCreatorCampanhaCampaignIdIndexRoute,
  recibosReciboMarcaCampanhaCampaignIdIndexRoute:
    recibosReciboMarcaCampanhaCampaignIdIndexRoute,
  recibosReciboMarcaCreatorCreatorIdCampaignIdIndexRoute:
    recibosReciboMarcaCreatorCreatorIdCampaignIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/",
        "/contrato-campanha/",
        "/privacidade/",
        "/termos/",
        "/cadastro/creator",
        "/cadastro/marca",
        "/cadastro/",
        "/esquecer-senha/",
        "/login/",
        "/recibo-creator/campanha/$campaignId/",
        "/recibo-marca/campanha/$campaignId/",
        "/recibo-marca/creator/$creatorId/$campaignId/"
      ]
    },
    "/": {
      "filePath": "(dashboard)",
      "children": [
        "/_side-nav-dashboard"
      ]
    },
    "/_side-nav-dashboard": {
      "filePath": "(dashboard)/_side-nav-dashboard.tsx",
      "parent": "/",
      "children": [
        "/_side-nav-dashboard/carteira-creator/",
        "/_side-nav-dashboard/carteira-marca/",
        "/_side-nav-dashboard/dashboard-creator/",
        "/_side-nav-dashboard/dashboard-marca/",
        "/_side-nav-dashboard/dashboard/",
        "/_side-nav-dashboard/notificacoes/",
        "/_side-nav-dashboard/top-creator/",
        "/_side-nav-dashboard/vitrine-de-campanhas/",
        "/_side-nav-dashboard/vitrine-de-creators/",
        "/_side-nav-dashboard/dashboard-marca/criar-campanha/",
        "/_side-nav-dashboard/dashboard-marca/rascunhos/",
        "/_side-nav-dashboard/dashboard/chat/",
        "/_side-nav-dashboard/entregaveis/$id/",
        "/_side-nav-dashboard/entregaveis/contrato/",
        "/_side-nav-dashboard/premium/creator/",
        "/_side-nav-dashboard/premium/ebooks/",
        "/_side-nav-dashboard/premium/marca/",
        "/_side-nav-dashboard/recursos/creator/",
        "/_side-nav-dashboard/recursos/marca/",
        "/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar",
        "/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar",
        "/_side-nav-dashboard/dashboard/campanhas/$campaignId/status",
        "/_side-nav-dashboard/creator/$username/",
        "/_side-nav-dashboard/marca/$userName/",
        "/_side-nav-dashboard/dashboard/campanhas/$campaignId/",
        "/_side-nav-dashboard/premium/creator/conteudos/",
        "/_side-nav-dashboard/creator/$username/editar/",
        "/_side-nav-dashboard/marca/$userName/editar/"
      ]
    },
    "/contrato-campanha/": {
      "filePath": "contrato-campanha/index.tsx"
    },
    "/privacidade/": {
      "filePath": "privacidade/index.tsx"
    },
    "/termos/": {
      "filePath": "termos/index.tsx"
    },
    "/cadastro/creator": {
      "filePath": "(auth)/cadastro/creator.tsx"
    },
    "/cadastro/marca": {
      "filePath": "(auth)/cadastro/marca.tsx"
    },
    "/cadastro/": {
      "filePath": "(auth)/cadastro/index.tsx"
    },
    "/esquecer-senha/": {
      "filePath": "(auth)/esquecer-senha/index.tsx"
    },
    "/login/": {
      "filePath": "(auth)/login/index.tsx"
    },
    "/_side-nav-dashboard/carteira-creator/": {
      "filePath": "(dashboard)/_side-nav-dashboard/carteira-creator/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/carteira-marca/": {
      "filePath": "(dashboard)/_side-nav-dashboard/carteira-marca/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard-creator/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard-creator/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard-marca/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard-marca/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/notificacoes/": {
      "filePath": "(dashboard)/_side-nav-dashboard/notificacoes/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/top-creator/": {
      "filePath": "(dashboard)/_side-nav-dashboard/top-creator/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/vitrine-de-campanhas/": {
      "filePath": "(dashboard)/_side-nav-dashboard/vitrine-de-campanhas/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/vitrine-de-creators/": {
      "filePath": "(dashboard)/_side-nav-dashboard/vitrine-de-creators/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard-marca/criar-campanha/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard-marca/criar-campanha/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard-marca/rascunhos/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard-marca/rascunhos/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard/chat/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/chat/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/entregaveis/$id/": {
      "filePath": "(dashboard)/_side-nav-dashboard/entregaveis/$id/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/entregaveis/contrato/": {
      "filePath": "(dashboard)/_side-nav-dashboard/entregaveis/contrato/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/premium/creator/": {
      "filePath": "(dashboard)/_side-nav-dashboard/premium/creator/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/premium/ebooks/": {
      "filePath": "(dashboard)/_side-nav-dashboard/premium/ebooks/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/premium/marca/": {
      "filePath": "(dashboard)/_side-nav-dashboard/premium/marca/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/recursos/creator/": {
      "filePath": "(dashboard)/_side-nav-dashboard/recursos/creator/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/recursos/marca/": {
      "filePath": "(dashboard)/_side-nav-dashboard/recursos/marca/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/recibo-creator/campanha/$campaignId/": {
      "filePath": "(recibos)/recibo-creator/campanha/$campaignId/index.tsx"
    },
    "/recibo-marca/campanha/$campaignId/": {
      "filePath": "(recibos)/recibo-marca/campanha/$campaignId/index.tsx"
    },
    "/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/aprovar.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/editar.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard/campanhas/$campaignId/status": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/status.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/creator/$username/": {
      "filePath": "(dashboard)/_side-nav-dashboard/(perfis)/creator/$username/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/marca/$userName/": {
      "filePath": "(dashboard)/_side-nav-dashboard/(perfis)/marca/$userName/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/dashboard/campanhas/$campaignId/": {
      "filePath": "(dashboard)/_side-nav-dashboard/dashboard/campanhas/$campaignId/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/premium/creator/conteudos/": {
      "filePath": "(dashboard)/_side-nav-dashboard/premium/creator/conteudos/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/recibo-marca/creator/$creatorId/$campaignId/": {
      "filePath": "(recibos)/recibo-marca/creator/$creatorId/$campaignId/index.tsx"
    },
    "/_side-nav-dashboard/creator/$username/editar/": {
      "filePath": "(dashboard)/_side-nav-dashboard/(perfis)/creator/$username/editar/index.tsx",
      "parent": "/_side-nav-dashboard"
    },
    "/_side-nav-dashboard/marca/$userName/editar/": {
      "filePath": "(dashboard)/_side-nav-dashboard/(perfis)/marca/$userName/editar/index.tsx",
      "parent": "/_side-nav-dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
